# yaml-language-server: $schema=../../../component-metadata-schema.json
schemaVersion: v1
type: nameresolution
name: kubernetes
version: v1
status: stable
title: "Kubernetes"
urls:
  - title: Reference
    url: https://docs.dapr.io/reference/components-reference/supported-name-resolution/nr-kubernetes/
metadata: []